# Alacritty config -- viz1er 

# fonts
font:
  normal:
    family: JetBrainsMono Nerd Font Mono 
    style: Regular
  bold:
    family: JetBrainsMono Nerd Font Mono 
    style: Bold
  italic: 
    family: JetBrainsMono Nerd Font Mono
    style: Italic
  bold_italic: 
    family: JetBrainsMono Nerd Font Mono
    style: Bold Italic

  size: 18

env:
  TERM: alacritty
  
window:

  dimensions: 
    columns: 200
    lines: 50
  padding: 
    x: 20
    y: 20

  opacity: 0.90

  class:
    instance: Alacritty
    general: Alacritty

scrolling:
  history: 10000
  multipler: 3

live_config_reload: true

schemes:
  # Tokyo Night theme, based on both:
  #   https://github.com/ghifarit53/tokyonight-vim
  #   https://github.com/enkia/tokyo-night-vscode-theme
  tokyo-night: &tokyo-night
    # Default colors
    primary:
      background: '#1a1b26'
      foreground: '#a9b1d6'

    # Normal colors
    normal:
      black:   '#32344a'
      red:     '#f7768e'
      green:   '#9ece6a'
      yellow:  '#e0af68'
      blue:    '#7aa2f7'
      magenta: '#ad8ee6'
      cyan:    '#449dab'
      white:   '#787c99'

    # Bright colors
    bright:
      black:   '#444b6a'
      red:     '#ff7a93'
      green:   '#b9f27c'
      yellow:  '#ff9e64'
      blue:    '#7da6ff'
      magenta: '#bb9af7'
      cyan:    '#0db9d7'
      white:   '#acb0d0'

  tokyo-night-storm: &tokyo-night-storm
    # Default colors
    primary:
      background: '#24283b'
      foreground: '#a9b1d6'

    # Normal colors
    normal:
      black:   '#32344a'
      red:     '#f7768e'
      green:   '#9ece6a'
      yellow:  '#e0af68'
      blue:    '#7aa2f7'
      magenta: '#ad8ee6'
      cyan:    '#449dab'
      white:   '#9699a8'

    # Bright colors
    bright:
      black:   '#444b6a'
      red:     '#ff7a93'
      green:   '#b9f27c'
      yellow:  '#ff9e64'
      blue:    '#7da6ff'
      magenta: '#bb9af7'
      cyan:    '#0db9d7'
      white:   '#acb0d0'

colors: *tokyo-night
