# $HOME/.config/alacritty
# by viz1er 

# Check all configs with `man 5 alacritty`

live_config_reload = true

[window]

opacity = 0.9
blur = true
dynamic_title = true
option_as_alt= "Both"

class.general = "Alacritty"
class.instance = "Alacritty"

dimensions.columns = 200
dimensions.lines = 50

padding.x = 20
padding.y = 20

[colors.bright]
black = "#444b6a"
blue = "#7da6ff"
cyan = "#0db9d7"
green = "#b9f27c"
magenta = "#bb9af7"
red = "#ff7a93"
white = "#acb0d0"
yellow = "#ff9e64"

[colors.normal]
black = "#32344a"
blue = "#7aa2f7"
cyan = "#449dab"
green = "#9ece6a"
magenta = "#ad8ee6"
red = "#f7768e"
white = "#787c99"
yellow = "#e0af68"

[colors.primary]
background = "#1a1b26"
foreground = "#a9b1d6"

[env]
TERM = "alacritty"

[font]
size = 18

normal.family = "JetBrainsMonoNL Nerd Font"
bold.family = "JetBrainsMonoNL Nerd Font"
italic.family = "JetBrainsMonoNL Nerd Font"
bold_italic.family = "JetBrainsMonoNL Nerd Font"

[scrolling]
history = 10000

[keyboard]
bindings = [
    { key = "Right", mods = "Alt", chars  = "\033f" }
    { key = "Left", mods = "Alt", chars = "\033b" }
]

# need to figure this out - https://github.com/alacritty/alacritty/issues/62 and https://github.com/alacritty/alacritty/issues/93 